export const OCCLUSION_ALGORITHM_TYPE_CONSERVATIVE = 1;
export const OCCLUSION_ALGORITHM_TYPE_ACCURATE = 2;
export type OCCLUSION_ALGORITHM_TYPE = typeof OCCLUSION_ALGORITHM_TYPE_CONSERVATIVE | typeof OCCLUSION_ALGORITHM_TYPE_ACCURATE;